### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by QkiZMR** [amiga-mui/muidev#324]
What happened with mui website? Where I can download lha files?

**Comment by jens-maus** [comment]
As you probably recognized. We are currently in the process of switching to GitHub for the MUI development. However, the nightly builds can still be downloaded from here: http://nightly.muidev.de/

In the near future, all the release files and nightly builds will, however, be moved over completly to GitHub and then stored in the releases section of this GitHub repository. So please stay tuned.

**Comment by nyteshade** [comment]
Any updates here? It's now March

**Comment by jens-maus** [comment]
Here you go:
https://github.com/amiga-mui/muidev/releases
