### ISSUE TITLE
Slider knob resets at the second click

### ISSUE THREAD

**Issue by hwsaddict** [amiga-mui/muidev#326]
System: OS4, MUI 5.0-2020R3
To check this, open the MUI preferences window Buttons page.
In the Slider frame doubleclick to the 3kg and the knob will reset to position 0.
Can't find if it is a documented feature or bug.
It is a disturbing behaviour I think.
MorphOS MUI not has this behaviour.

**Comment by tboeckel** [comment]
This will be disabled from the next nightly build on.
