### ISSUE TITLE
Setting MUIA_FrameTitle

### ISSUE THREAD

**Issue by softwarefailure** [amiga-mui/muidev#327]
I'm getting lots of requests from people who want to be able to set a group's frame title but `MUIA_FrameTitle` just has an applicability of I. Any chance this could be extended to be settable as well? Or is there any other way to set a group's frame title? Thanks!

**Comment by tboeckel** [comment]
Guess what, that attribute is in fact ISG instead of I.. since ages already. Your documentation (MUI 3.8?) is just utterly outdated. Take a look [here](https://github.com/amiga-mui/muidev/wiki/MUI_Area#MUIA_FrameTitle).
