### ISSUE TITLE
Setting MUIA_FrameTitle causes complete refresh

### ISSUE THREAD

**Issue by softwarefailure** [amiga-mui/muidev#328]
I've noticed that setting `MUIA_FrameTitle` will always refresh the whole group and there's a clearly visible glitch because the group will move down a little and then move up again. This looks rather ugly. On MorphOS it doesn't happen and only the frame title is refreshed without making the group jump down and up again.

**Comment by tboeckel** [comment]
Fixed in the next nightly build.
I know, the nightly builds are not yet up and running again, but since setting MUIA_FrameTitle is working, although with a larger refresh than necessary, this is no real show stopper.
