### ISSUE TITLE
Can't open menu when set "Enable embedded menu bar"

### ISSUE THREAD

**Issue by samo79** [amiga-mui/muidev#331]
I've originally reported it on the iGame repo

https://github.com/MrZammler/iGame/issues/144

Menu does not seems to work anymore in iGame if you set "Enable embedded menu bar" from MUI prefs ... options are showed in the main window but they can't be opened  Tested with iGame 2.1 Beta 1 under AmigaOS 4.1 FE (latest MUI 5.0)

**Comment by tboeckel** [comment]
The menu might be built from Menu objects and Menuitem objects, but Menudisplay checked MUIA_Menu_Enabled only to be true. For Menuitem object this of course is never true and hence the item was considered to be disabled. Now the class is checked before the corresponding enabled state is checked.

[Menudisplay_21_27_os3.zip](https://github.com/amiga-mui/muidev/files/6179770/Menudisplay_21_27_os3.zip)
[Menudisplay_21_27_os4.zip](https://github.com/amiga-mui/muidev/files/6179772/Menudisplay_21_27_os4.zip)

**Comment by samo79** [comment]
Ok tested, but got a crash

[Crashlog_iGame.OS4_2021-03-22_17-51-19.txt](https://github.com/amiga-mui/muidev/files/6183926/Crashlog_iGame.OS4_2021-03-22_17-51-19.txt)

**Comment by samo79** [comment]
Crash is reproducible in all MUI applications, i've revert for now waiting for a proper implementation :-)

**Comment by tboeckel** [comment]
This crash seems to be related to some internal changes since 5.0-2020R3. The location of the crash is **before** the latest change...

**Comment by tboeckel** [comment]
We really need to get the nightly build up and running again :(

**Comment by tboeckel** [comment]
[MUI-5.0-20210324-0d266f2-os4.zip](https://github.com/amiga-mui/muidev/files/6194883/MUI-5.0-20210324-0d266f2-os4.zip)

Please try this private nightly build for AmigaOS4.

**Comment by samo79** [comment]
Yeah seems you fixes the issue, bravo :-)
Ticket can be closed now..

About MUI development, frankly I was felt better with the old system .. apart from not being able to use the Amiga to report bugs (github does not work with Odyssey) it is not clear how we betatesters can follow its progress in details .... once the switch will be completed I hope that at least the periodically updated changelog file could be publicly available for reading/consulting ...
