### ISSUE TITLE
Showing Aboutbox window crashes badly

### ISSUE THREAD

**Issue by rzookol** [amiga-mui/muidev#332]
using bebbo gcc6 environment:
m68k-amigaos-gcc  Aboutbox.c -oAboutbox -I. -DNO_INLINE_STDARG -lmui

Aboutbox example crashes after clicking on button, other application compiled by myself also crashes  badly  before showing aboutbox window.

Tested with 2 mui releases from:
http://nightly.muidev.de/

Hyperlink from
m68k-amigaos-gcc  -noixemul  Hyperlink.c -oHyperlink -I. -DNO_INLINE_STDARG -lmui 

works without problem so standalone mcc's work ok.

**Comment by tboeckel** [comment]
Well, the demos supplied with each release or nightly build archive definitely do work. If your own build crashes, then this is beyond the scope of MUI.
You state yourself that you are building the Aboutbox demo differently than the Hyperlink demo (-noixemul option) and then complain about crashes of one demo while the other one work. Perhaps you should start to build both demos in the same way...

**Comment by tboeckel** [comment]
Any further comments or progress here?

**Comment by tboeckel** [comment]
No answer since 2 months, closing this one.
