### ISSUE TITLE
Setting MUIA_List_SortColumn changes sort order

### ISSUE THREAD

**Issue by softwarefailure** [amiga-mui/muidev#336]
Take a look at the attached sample. Press the button, it will make column 1 the sort column. This works correctly. Now press the button again. Surprisingly, the sort order of column 1 will be reversed now. This shouldn't happen. Pressing the button a second time should do nothing since column 1 is the sort column already.
[main.txt](https://github.com/amiga-mui/muidev/files/6511192/main.txt)

**Comment by tboeckel** [comment]
Fixed in the next nightly build.
