### ISSUE TITLE
Changing sort order doesn't work

### ISSUE THREAD

**Issue by softwarefailure** [amiga-mui/muidev#337]
I want to change the sort order from ascending to descending so I set a new `MUIA_List_Format` string. When doing so, the arrow image in the header is correctly changed from ascending to descending but the list is not resorted. Check the attached example. Press the button to change sort order of column 0 from ascending to descending. As you can see, only the arrow image in the header changes but the list is not resorted.
[main2.txt](https://github.com/amiga-mui/muidev/files/6511200/main2.txt)

**Comment by tboeckel** [comment]
Fixed in the next nightly build.
