### ISSUE TITLE
Recent 5.0 release complains about being out of date immediately after install

### ISSUE THREAD

**Issue by siborg** [amiga-mui/muidev#339]
Just installed MUI-5.0-2020R3-os3 - unfortunately it straight away errors that  "This version of MUI has expired". This is the release from 2 days ago.

**Comment by tboeckel** [comment]
That one is not the 2020R3 release, but a nightly build from a few weeks ago. The official 2020R3 release has muimaster.library 21.210 (svn r6714) included and has definitely no time limit.
New nightly builds can be found [here](https://github.com/amiga-mui/muidev/releases/snapshots)
