### ISSUE TITLE
MUIA_Listtree_Active doesn't work from MUIM_CallHook

### ISSUE THREAD

**Issue by softwarefailure** [amiga-mui/muidev#340]
When making MUI call a hook whenever `MUIA_Listtree_Active` changes, it seems like that at the time the hook gets called, `MUIA_Listtree_Active` doesn't return the correct active item. Take a look at the example attached. If you select an item, `MUIA_Listtree_Active` will still return NULL in the call hook. After that, `MUIA_Listtree_Active` will always return the *previously* active item so it looks like that at the time the hook gets called, `MUIA_Listtree_Active` still returns the old state.

[main.txt](https://github.com/amiga-mui/muidev/files/6564682/main.txt)

**Comment by tboeckel** [comment]
You are right. The notification was triggered before the new treenode was set. Fixed in the next nightly build.
