### ISSUE TITLE
Is it possible to programmatically turn off highlighting the sort column?

### ISSUE THREAD

**Issue by softwarefailure** [amiga-mui/muidev#342]
When using sortable listview columns, the column that has the sort focus is highlighted by MUI. I know this can be configured in the prefs but is it also possible to disable this highlighting programmatically? If not, consider this a feature request.

**Comment by tboeckel** [comment]
Short answer: no
Long answer: no, this is a user setting, just like the color of the the selected list row. If the user doesn't like the highlighting it is the job of the user to change that
