### ISSUE TITLE
ORDER=DESC doesn't work

### ISSUE THREAD

**Issue by softwarefailure** [amiga-mui/muidev#345]
Take a look at the attached example. Setting ORDER=DESC in `MUIA_List_Format` doesn't do anything at all. 
[main.txt](https://github.com/amiga-mui/muidev/files/6796933/main.txt)

**Comment by tboeckel** [comment]
Is setting ORDER without setting SORTABLE supposed to work? If you make your column sortable then everything works as expected.

**Comment by softwarefailure** [comment]
But according to the docs the SORTABLE flag is just for allowing the user to allow sorting by clicking on the header. I think setting ORDER=DESC makes perfect sense without SORTABLE. Imagine a listview without a header and you won't descending sort order. So you'd set ORDER=DESC but not SORTABLE because there is no header.

**Comment by tboeckel** [comment]
Fixed in the next nightly build.
