### ISSUE TITLE
Order's of mui key?! 

### ISSUE THREAD

**Issue by trgswe** [amiga-mui/muidev#346]
Why is it that if you order a mui key... nothing happens

this is why amigaos 4.1 MUST remove all traces of MUI from any programs running on it... perhaps a mui->reaction wrapper library?

**Comment by tboeckel** [comment]
Creating a MUI key is beyond our scope and beyond our control. And we are not allowed to remove the key file mechanism. Blame it on Stefan Stuntz and the MorphOS team.

**Comment by jens-maus** [comment]
Besides that: in OS4 use most of the features should be available to end users even without keyfile and the default look&feel mimics the default os4 look&feel. So which features are yOu missing?

**Comment by trgswe** [comment]
My system does NOT look like the default OS4 system on look or feel


Den ons 14 juli 2021 08:09Jens Maus ***@***.***> skrev:
