### ISSUE TITLE
ORDER=DESC brings up Grim Reaper

### ISSUE THREAD

**Issue by softwarefailure** [amiga-mui/muidev#348]
Take a look at the attached example. This brings up the Grim Reaper on OS4. Tested with the July 14th nightly.
[main.txt](https://github.com/amiga-mui/muidev/files/6818009/main.txt)

**Comment by tboeckel** [comment]
Please provide a crashlog

**Comment by softwarefailure** [comment]
Seems to have been fixed. Can't reproduce it any more with July 16th nightly.
