### ISSUE TITLE
Setting MUIA_List_SortColumn at initialization time doesn't work

### ISSUE THREAD

**Issue by softwarefailure** [amiga-mui/muidev#350]
Take a look at the attached example. It sets the second column as the sort column at initialization time. However, it doesn't work. Entries appear as E,F,G,H in the second column but they should appear as H,G,F,E because `ORDER=DESC` has been set for the column.
[main.txt](https://github.com/amiga-mui/muidev/files/6831217/main.txt)

**Comment by tboeckel** [comment]
Fixed in the next nightly build.
