### ISSUE TITLE
Listview: Auto column width calculation ignores sorting arrow

### ISSUE THREAD

**Issue by mrupp12bit** [amiga-mui/muidev#351]
Hi there
It's not a biggy but still worth mentioning, imho.

If a column's width is calculated automatically by its cell values and caption, the headers sorting arrow is not included in this calulation and is truncated in case the caption holds the longest text. Here are some screenshots to illustrate this:

As is:
![image](https://user-images.githubusercontent.com/38189288/126217182-1b6eab89-292d-4edc-af51-92acc0716eda.png)

As expected:
![image](https://user-images.githubusercontent.com/38189288/126217200-f275bb69-7186-4e75-b444-faaca0b8b078.png)

Cheers, Michael

**Comment by tboeckel** [comment]
Fixed in the next nightly build.

**Comment by mrupp12bit** [comment]
Tested with the 20210725 nightly and works! Thanks for fixing this.
