### ISSUE TITLE
MUIA_List_SortColumn returns -1 in compare hook

### ISSUE THREAD

**Issue by softwarefailure** [amiga-mui/muidev#352]
With the July 21st nightly, `MUIA_List_SortColumn` suddenly reports -1 in the compare hook which makes all hell break loose. Take a look at the attached example. It will crash upon startup in this line:

```
get(data->obj, MUIA_List_SortColumn, &sortcolumn);
return strcmp(entry1[sortcolumn], entry2[sortcolumn]); 
```

because `sortcolumn` is -1.
[main.txt](https://github.com/amiga-mui/muidev/files/6855214/main.txt)

**Comment by tboeckel** [comment]
Fixed in the next nightly build.
