### ISSUE TITLE
MUIMaster.library entry in Wiki

### ISSUE THREAD

**Issue by SamuraiCrow** [amiga-mui/muidev#353]
MuiMaster.library entry in the MUIDev Wiki points to a link which doesn't register with my browser.  When I try clicking the link it only opens a blank page to edit and yields the error code:  Couldn't find version Master.  Is it pointing to a document I don't have access to?  Perhaps copying the text file directly to the Wiki would help.

Side note:  Why do I have edit privilages enabled for the Wiki?

**Comment by tboeckel** [comment]
I just changed to source location for that single file. For me it works.

Are sure you really have editing capabilities? Did you try to edit an existing file or really create a new file?

**Comment by SamuraiCrow** [comment]
https://github.com/amiga-mui/muidev/wiki/This-shouldn't-be-here

The MUIMaster autodoc works though.

**Comment by tboeckel** [comment]
Thanks for the hint. We will resolve this.

**Comment by SamuraiCrow** [comment]
Should be a single check-box called "limit wiki access to contributors" or something like that.
