### ISSUE TITLE
Switch MUIA_String_Secret on the fly

### ISSUE THREAD

**Issue by walkero-gr** [amiga-mui/muidev#354]
Is it possible to switch a string field that is set with MUIA_String_Secret to TRUE, to FALSE on the fly? Let's say that I have a password field which I would like the user to be able to show, if he clicks on a button.

It tried with set() and with DoMethod(), but it didn't work. Or I might miss something.

Do you have any recommendation or a hint for this?

Thank you for your help.

**Comment by tboeckel** [comment]
MUIA_String_Secret is in fact OM_SET'able, although the documentation does not (yet) reflect this fact. The real bug is that the String object is not updated graphically when MUI_String_Secret is modified.

**Comment by tboeckel** [comment]
Fixed in the next nightly build.
